apiVersion: configmanagement.gke.io/v1
kind: ConfigManagement
metadata:
  name: config-management
  namespace: config-management-system
spec:
  clusterName: asm-testing
  git:
    syncRepo: https://github.com/adrienafl/csp-config-management.git
    syncBranch: 1.0.0
    secretType: none
    policyDir: "hello-namespace/config-root"
  policyController:
    enabled: true
    exemptableNamespaces: ["helloworld","config-management-system","default","gke-connect","istio-system","kube-node-lease","kube-public","kube-system"]
  configConnector:
    enabled: true
